# set the language 
language: go 
go_import_path: github.com/MarcInthaamnouay/GoColorPicker
sudo: false
go: 
  - 1.8

before_install:
  # Exporting the Golang config
  - export GOPATH=/home/travis/gopath/src/github.com/MarcInthaamnouay/GoColorPicker
  # Download & install nvm 
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
  - nvm install node
  - npm install --global mocha
  - npm install --global should 

install: 
  # Install the dependencies for testing 
  - go get github.com/stretchr/testify

before_script:
  - go build src/start.go

script: 
  # Launch the go test 
  - go test -v src/test/color_test.go
  # Launch the JavaScript test 
  - ./node_modules/mocha/bin/mocha