language: go 
go_import_path: github.com/MarcInthaamnouay/GoColorPicker
sudo: false
go: 
  - 1.8

install: 
  # Install the dependencies for testing 
  - go get github.com/stretchr/testify

before_install:
  - export GOPATH=/home/travis/gopath/src/github.com/MarcInthaamnouay/GoColorPicker

before_script:
  - ls -la
  - pwd
  - echo $GOPATH
  - go build src/start.go

script: 
  # Launch the go test 
  - go test -v src/test/color_test.go