language: go 
go_import_path: github.com/MarcInthaamnouay/GoColorPicker
go: 
  - 1.8

env:
  - "GOPATH=/home/travis/gopath/src/github.com/MarcInthaamnouay/GoColorPicker"

install: 
  # Install the dependencies for testing 
  - go get github.com/stretchr/testify

before_script:
  - go install src/start.go

script: 
  # Launch the go test 
  - go test -v src/test/color_test.go
